name: Build On EC2 Runner

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, integration]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print workspace path
        run: echo "Workspace path:$GITHUB_WORKSPACE" 
